### PR TITLE
add iterable support

### PR DESCRIPTION
**Pull request by glundy1984**

### CODE REVIEW

**Comment by bramp** [comment]
Thanks for the pull request!

Can you explain in what situation you would need this? Today if we descend into a ArrayList for example, we pull out the internal array field and reach all elements.

Previously we would not call methods on the objects. This code worries me as a iterator's next method could continue to create elements forever, and we get stuck

**Comment by glundy1984** [comment]
Hi Andrew,

I need to visit each object in a graph and if the object implements a particular interface then update a particular field.

The object graph is an ORM hibernate graph and therefore contains Lists and not basic arrays.

In the test I created your current code does not process or dive into Lists. The small piece of code I added allows your code to delve into ArrayLists and more generally Iterables.

In the simple tests I created so far my update appears to do what I want.

I’m not sure I understand your point about an iterator generating elements forever… surely there are a finite number of elements in the iterator?

I’ll put more thought into it and do some tests on more complicated graphs when I get some time.

Thanks for your work. :)

Regards
Gerard

**Comment by bramp** [comment]
I just pushed fc813cff686d to show that the ObjectGraph will descend into a List/Collection, and not just basic arrays. It does this, because fundamentally all Collections store the elements in an array or similar private field within the class.

I think the reason you have a problem with Hibernate list, is that Hibernate can lazy load collections, and only fetch them from the database on request. This database query is triggered when you iterate the list. Until that point the list has no actual elements in memory.

The problem I have with calling a iterator, or any other method, is that method could change the state of the object, or otherwise do something bad that crashes the problem. Right now, the way ObjectGraph works is to never call methods, and just inspect fields. I'm concerned that calling the iterator's next(), could cause a infinite loop (due to it changing state in the object).

To solve your problem in particular, I suggest you force Hibernate to load the data before passing it to the ObjectGraph. For example, calling [Hibernate.initialize](https://docs.jboss.org/hibernate/orm/3.5/api/org/hibernate/Hibernate.html#initialize%28java.lang.Object%29) or not fetching lazily.

I'm still happy to discuss this issue, but unless I'm missing something I don't think your change is appropriate to be accepted.

**Comment by glundy1984** [comment]
The test I performed was on a simple object tree with Lists and did not involve Hibernate.

I understand your point, that your code should jump into a Collection and then iterate over the inner array and other objects.

Maybe I have done something wrong and I will investigate further. If I find an issue I’ll produce a demo app comparing the differences and send it to you.

Apologies if I have wasted your time.

Gerard

**Comment by bramp** [comment]
Yes, if you can reproduce the list not working, then please send a demo app, or better yet a simple unit test that shows the broken behaviour. No time wasted, you have reminded me of this project I hadn't touched in a year :)

Closing for now, but please reopen if there is a confirmed problem.

**Comment by glundy1984** [comment]
I also like your idea of adding an exclusion list.

For my purposes it provides no benefit of entering a String object and returning each element of its char array.

Also adding the option to handle iterables would allow your code to ignore the inner implementation of classes like ArrayList, LinkedList etc and only work with the elements we are concerned with.
If you are concerned about its safety allowing the user to toggle the feature similar to excludeTransient and excludeStatic could be option.

Anyway I’ll try to reproduce this issue I discovered, if it exists.

Gerard

**Comment by bramp** [comment]
Agreed on exclusion/ignoring inner-workings of a class. But the actual point of this code was to traverse the object graph, which includes the inner workings :)

Perhaps I can make the visitor callback more expressive, allowing the user to decide if they wish to go deeper or not.

**Pull request closed without merging**
